//
//  Event-All.swift
//  App
//
//  Created by Julian Schiavo on 17/5/2019.
//

import Foundation

extension JSONEvent {
    static var all: [JSONEvent] {
        return [
            
            // MARK: Special Events
            
            JSONEvent(id: "ScholarshipKickoff",
                      tag: .specialEvent,
                      requiredKind: "Scholar",
                      title: "Scholarship Kickoff",
                      description: "Scholarship recipients, chaperones, and all attendees under 18 years old are invited to the Scholarship Kickoff. Join us at Discovery Meadow for lunch, games, conversations with Apple engineers and staff, and more. ",
                      startDate: .default(day: 2, hour: 12, minute: 30),
                      endDate: .default(day: 2, hour: 16, minute: 0),
                      latitude: 37.3278,
                      longitude: -121.8925),
            
            JSONEvent(id: "Keynote",
                      tag: .specialEvent,
                      title: "Keynote",
                      description: "To kick off WWDC, Tim Cook will deliver the opening keynote, where he will announce upcoming software upgrades and new features.",
                      startDate: .default(day: 3, hour: 10, minute: 0),
                      endDate: .default(day: 3, hour: 12, minute: 0),
                      latitude: 37.3298,
                      longitude: -121.8888),
            
            JSONEvent(id: "StateOfTheUnion",
                      tag: .specialEvent,
                      title: "Platforms State of the Union",
                      description: "Learn more about the new features and technologies announced in the Keynote and how to take advantage of them in your own apps at the WWDC19 Platforms State of the Union.",
                      startDate: .default(day: 3, hour: 14, minute: 30),
                      endDate: .default(day: 3, hour: 16, minute: 30),
                      latitude: 37.3298,
                      longitude: -121.8888),
            
            JSONEvent(id: "AppleDesignAwards",
                      tag: .specialEvent,
                      title: "Apple Design Awards",
                      description: "The Apple Design Awards recognize state of the art iOS, macOS, watchOS, and tvOS apps that reflect excellence in design and innovation. Join us for an unforgettable award ceremony celebrating developers and their outstanding work.",
                      startDate: .default(day: 3, hour: 17, minute: 0),
                      endDate: .default(day: 3, hour: 18, minute: 0),
                      latitude: 37.3298,
                      longitude: -121.8888),
            
            JSONEvent(id: "Bash",
                      tag: .specialEvent,
                      title: "The Bash",
                      description: "Experience incredible music, food, and drinks at Discovery Meadow, just steps away from the McEnery Convention Center.",
                      startDate: .default(day: 6, hour: 19, minute: 0),
                      endDate: .default(day: 6, hour: 22, minute: 0),
                      latitude: 37.3278,
                      longitude: -121.8925),
            
            // MARK: Podcasts
            
            JSONEvent(id: "AccidentalTechPodcast",
                      tag: .podcast,
                      title: "Accidental Tech Podcast",
                      description: "A live recording of the WWDC Accidental Tech Podcast at the Hammer Theatre. No WWDC ticket needed.",
                      startDate: .default(day: 3, hour: 18, minute: 0),
                      endDate: .default(day: 3, hour: 20, minute: 0),
                      place: "Hammer Theatre",
                      latitude: 37.3337,
                      longitude: -121.8865,
                      ticketLink: "http://atp.fm/wwdc"),
            
            JSONEvent(id: "TheTalkShow",
                      tag: .podcast,
                      title: "The Talk Show with John Gruber Live",
                      description: "Renowned columnist and podcaster John Gruber of Daring Fireball discusses the latest trends in technology and design. More details coming soon.",
                      startDate: .default(day: 4, hour: 19, minute: 0),
                      endDate: .default(day: 4, hour: 21, minute: 0),
                      place: "California Theatre",
                      latitude: 37.3308,
                      longitude: -121.887,
                      ticketLink: "https://daringfireball.net/thetalkshow/live"),
            
            JSONEvent(id: "SwiftOverCoffeePodcast",
                      tag: .podcast,
                      title: "Swift over Coffee Live",
                      description: "Swift over Coffee is celebrating WWDC19 with a special expanded podcast event with guest hosts and lots of discussion of what's new from Cupertino! They'll also be joined by Kristina Fox, Gui Rambo, JP Simard, and Kaya Thomas as we dive into the major changes from WWDC19, what we're excited about, and how it will impact Swift developers over the next 12 months.",
                      startDate: .default(day: 5, hour: 17, minute: 30),
                      endDate: .default(day: 5, hour: 18, minute: 30),
                      place: "San Jose Marriott",
                      latitude: 37.3302,
                      longitude: -121.8885,
                      ticketLink: "https://ti.to/altconf/SwiftoverCoffeeLive"),
            
            JSONEvent(id: "ConnectedPodcast",
                      tag: .podcast,
                      title: "Connected by Relay FM",
                      description: "Gathered from the far corners of the globe, the Connected hosts make their annual trip to California to talk about WWDC, Apple's announcements and the response from the community in what promises to be the most entertaining live podcast of the week.",
                      startDate: .default(day: 5, hour: 18, minute: 0),
                      endDate: .default(day: 5, hour: 20, minute: 0),
                      place: "Hammer Theatre",
                      latitude: 37.3337,
                      longitude: -121.8865,
                      ticketLink: "https://hammertheatre.vbotickets.com/event/Relay_FM_Connected_Podcast/33940"),
            
            JSONEvent(id: "JamesDempseyAndTheBreakpoints",
                      tag: .podcast,
                      title: "James Dempsey and the Breakpoints",
                      description: "Live Near WWDC 2019: Join the iTunes chart-topping nerd band for a night of original programming-oriented music and humor to benefit App Camp For Girls",
                      startDate: .default(day: 5, hour: 19, minute: 0),
                      endDate: .default(day: 5, hour: 23, minute: 0),
                      place: "The Ritz San Jose",
                      latitude: 37.3301,
                      longitude: -121.8856,
                      ticketLink: "https://livenearwwdc.com"),
            
            // MARK: Meetups
            
            // Official
            
            JSONEvent(id: "WomenBreakfast",
                      tag: .meetup,
                      title: "Women@WWDC Breakfast",
                      description: "Open to all attendees, these informal breakfasts are a great way to meet some of the phenomenal people at WWDC while you start your day with a buffet. This engaging panel discussion features Apple Entrepreneur Camp alumni and female WWDC Scholarship recipients. Moderated by Dawn Dagucon, Program Manager, Apple Entrepreneur Camp.",
                      startDate: .default(day: 4, hour: 7, minute: 30, second: 0),
                      endDate: .default(day: 4, hour: 8, minute: 30, second: 0),
                      place: "Hilton San Jose",
                      latitude: 37.3293,
                      longitude: -121.8905),
            
            JSONEvent(id: "AccessibilityGetTogetherMorning",
                      tag: .meetup,
                      title: "Accessibility Get-Together",
                      description: "Bring your lunch and engage in casual conversations about accessibility with fellow developers, Apple engineers, and members of the Apple accessibility team. Meet Apple engineers who regularly use VoiceOver and Switch Control to chat about apps they use at work and how they recommend developing accessibility features. Set up the Accessibility Shortcut and show us how you can use VoiceOver to navigate your app or any app you choose. Successful navigators earn an accessibility pin.",
                      startDate: .default(day: 4, hour: 11, minute: 30, second: 0),
                      endDate: .default(day: 4, hour: 12, minute: 30, second: 0),
                      place: "Market Terrace, San Jose McEnery Convention Center",
                      latitude: 37.3298,
                      longitude: -121.8888),
            
            JSONEvent(id: "AccessibilityGetTogetherEvening",
                      tag: .meetup,
                      title: "Accessibility Get-Together",
                      description: "Join fellow developers and Apple experts to explore the many ways that apps can be accessible and inclusive. Discover how Siri Shortcuts, ARKit, the TrueDepth Camera, and CoreML can be leveraged for accessibility, and see examples of apps that have taken care to design excellent experiences for VoiceOver and Switch Control users. Set up the Accessibility Shortcut and show us how you can use VoiceOver to navigate your app or any app you choose. Successful navigators earn an accessibility pin.",
                      startDate: .default(day: 4, hour: 16, minute: 0, second: 0),
                      endDate: .default(day: 4, hour: 17, minute: 30, second: 0),
                      place: "Market Terrace, San Jose McEnery Convention Center",
                      latitude: 37.3298,
                      longitude: -121.8888),
            
            JSONEvent(id: "OfficialNikeRun",
                      tag: .meetup,
                      title: "Official WWDC Run with Joan Benoit Samuelson",
                      description: "Celebrate Global Running Day with an invigorating run through San Jose led by the amazing Joan Benoit Samuelson, winner of the Boston Marathon, the Chicago Marathon, and the first ever Women’s Olympic Marathon. Check-in starts at 6:30 a.m. WWDC19 ticket required.",
                      startDate: .default(day: 5, hour: 7, minute: 0),
                      endDate: .default(day: 5, hour: 8, minute: 0),
                      latitude: 37.3298,
                      longitude: -121.8888),
            
            JSONEvent(id: "BlackBreakfast",
                      tag: .meetup,
                      title: "Black@WWDC Breakfast",
                      description: "Open to all attendees, these informal breakfasts are a great way to meet some of the phenomenal people at WWDC while you start your day with a buffet. Hear from talented developers who use technology to help individuals from underrepresented communities pursue careers in tech. Moderated by Stacy Ishmael, Senior Editor, App Store.",
                      startDate: .default(day: 5, hour: 7, minute: 30, second: 0),
                      endDate: .default(day: 5, hour: 8, minute: 30, second: 0),
                      place: "Hilton San Jose",
                      latitude: 37.3293,
                      longitude: -121.8905),
            
            JSONEvent(id: "WellnessGetTogetherMorning",
                      tag: .meetup,
                      title: "Wellness Get-Together",
                      description: "Bring your lunch and your passion for health and fitness to casual conversations with fellow developers and Apple staff. Discuss the many ways HealthKit, ResearchKit, and CareKit can be used to create outstanding wellness apps for iPhone and Apple Watch.",
                      startDate: .default(day: 5, hour: 11, minute: 30, second: 0),
                      endDate: .default(day: 5, hour: 12, minute: 30, second: 0),
                      place: "Market Terrace, San Jose McEnery Convention Center",
                      latitude: 37.3298,
                      longitude: -121.8888),
            
            JSONEvent(id: "WellnessGetTogetherEvening",
                      tag: .meetup,
                      title: "Wellness Get-Together",
                      description: "Learn about the development of Apple’s ECG app for Apple Watch, directly from leaders of the Apple health team, followed by a discussion on heart health.",
                      startDate: .default(day: 5, hour: 17, minute: 0, second: 0),
                      endDate: .default(day: 5, hour: 18, minute: 0, second: 0),
                      place: "Market Terrace, San Jose McEnery Convention Center",
                      latitude: 37.3298,
                      longitude: -121.8888),
            
            JSONEvent(id: "LatinxBreakfast",
                      tag: .meetup,
                      title: "Latinx@WWDC Breakfast",
                      description: "Open to all attendees, these informal breakfasts are a great way to meet some of the phenomenal people at WWDC while you start your day with a buffet. Gain insights from Latinx developers creating incredible apps for Apple platforms. Moderated by Melinda Borjon Heinlein, Apple Worldwide Developer Relations.",
                      startDate: .default(day: 6, hour: 7, minute: 30, second: 0),
                      endDate: .default(day: 6, hour: 8, minute: 30, second: 0),
                      place: "Hilton San Jose",
                      latitude: 37.3293,
                      longitude: -121.8905),
            
            JSONEvent(id: "EducationGetTogetherMorning",
                      tag: .meetup,
                      title: "Education Get-Together",
                      description: "Bring your lunch and engage in casual conversations with fellow developers and members of the Apple education team. Topics include coding education, games in education, augmented reality in education, and more.",
                      startDate: .default(day: 6, hour: 11, minute: 30, second: 0),
                      endDate: .default(day: 6, hour: 12, minute: 30, second: 0),
                      place: "Market Terrace, San Jose McEnery Convention Center",
                      latitude: 37.3298,
                      longitude: -121.8888),
            
            JSONEvent(id: "EducationGetTogetherEvening",
                      tag: .meetup,
                      title: "Education Get-Together",
                      description: "Join fellow developers and Apple experts to experience and discuss innovations in education technology. Explore apps that use ARKit to create delightful and immersive learning experiences, and see how CoreML can be leveraged to benefit learners. Try out robotics coding challenges with Swift Playgrounds, and learn how teachers can use Schoolwork to assign students activities within apps.",
                      startDate: .default(day: 6, hour: 16, minute: 0, second: 0),
                      endDate: .default(day: 6, hour: 17, minute: 30, second: 0),
                      place: "Market Terrace, San Jose McEnery Convention Center",
                      latitude: 37.3298,
                      longitude: -121.8888),
            
            JSONEvent(id: "AppDesignGetTogether",
                      tag: .meetup,
                      title: "App Design Get-Together",
                      description: "Bring your lunch and engage in casual conversations with fellow developers and Apple staff on designing apps for everyone. You can ask questions, and share your learnings or success stories. Get inspired, share experiences, and envision new possibilities together.",
                      startDate: .default(day: 7, hour: 11, minute: 30, second: 0),
                      endDate: .default(day: 7, hour: 12, minute: 30, second: 0),
                      place: "Market Terrace, San Jose McEnery Convention Center",
                      latitude: 37.3298,
                      longitude: -121.8888),
            
            // Third Party
            
            JSONEvent(id: "CoreSushi",
                      tag: .meetup,
                      title: "Core Sushi 6.0",
                      description: "The 6th year of delicious omakase with fellow developers on the Saturday evening before WWDC! Plan on $70/person for the night - includes food, drink, and tip.",
                      startDate: .default(day: 1, hour: 19, minute: 0, second: 0),
                      endDate: .default(day: 1, hour: 21, minute: 0, second: 0),
                      place: "Furusato Sushi",
                      latitude: 37.2863,
                      longitude: -121.9794,
                      ticketLink: "https://www.evite.com/event/03D7IE2EO62OAA5DWEPJJHGT7R6KNA/rsvp"),
            
            JSONEvent(id: "sjMacIndie",
                      tag: .meetup,
                      title: "sjMacIndie",
                      description: "sjMacIndie is the premier networking event that kicks off WWDC. It is for independent macOS and iOS developers, designers, and anyone else who's interested. It is a great opportunity to connect and network!",
                      startDate: .default(day: 2, hour: 17, minute: 0, second: 0),
                      endDate: .default(day: 2, hour: 21, minute: 0, second: 0),
                      place: "Forager",
                      latitude: 37.3298,
                      longitude: -121.8855,
                      moreInfoLink: "http://sfmacindie.com"),
            
            JSONEvent(id: "DubDubRun030619",
                      tag: .meetup,
                      title: "Dub Dub Run",
                      description: "Kick off your mornings right with an easy 5k jog along the scenic Guadalupe River while chattting about all the fun stuff announced at WWDC.",
                      startDate: .default(day: 3, hour: 7, minute: 20),
                      endDate: .default(day: 3, hour: 8, minute: 0),
                      latitude: 37.331,
                      longitude: -121.894,
                      moreInfoLink: "https://dubdub.fitness/run.html"),
            
            JSONEvent(id: "NightOfDimSum030619",
                      tag: .meetup,
                      title: "Night of Dim Sum 2019",
                      description: "Join us for a night of all-you-can-eat dim sum! Located just a couple of miles from downtown San Jose in the Westfield Valley Fair Mall (where there is also an Apple Store and a LEGO store), Din Tai Fung is internationally known as one of the world's best Shanghai dumpling restaurants.",
                      startDate: .default(day: 3, hour: 19, minute: 0),
                      endDate: .default(day: 3, hour: 21, minute: 0),
                      place: "Din Tai Fung (Westfield Valley Fair Mall)",
                      latitude: 37.3261,
                      longitude: -121.9441,
                      ticketLink: "https://www.eventbrite.com/e/night-of-dim-sum-2019-tickets-54087628553"),
            
            JSONEvent(id: "TheLoopBash",
                      tag: .meetup,
                      title: "The Loop Bash",
                      description: "Join Jim Dalrymple of The Loop for his annual party celebrating the developer community, featuring an incredible night of live music.",
                      startDate: .default(day: 3, hour: 20, minute: 0, second: 0),
                      endDate: .default(day: 3, hour: 24, minute: 0, second: 0),
                      place: "The Ritz",
                      latitude: 37.3300,
                      longitude: -121.8857,
                      ticketLink: "https://ti.to/jim-dalrymple/the-loop-bash-at-wwdc",
                      moreInfoLink: "http://www.loopinsight.com/2019/05/22/the-loop-bash-at-wwdc-2019/"),
            
            JSONEvent(id: "DubDubRun040619",
                      tag: .meetup,
                      title: "Dub Dub Run",
                      description: "Kick off your mornings right with an easy 5k jog along the scenic Guadalupe River while chattting about all the fun stuff announced at WWDC.",
                      startDate: .default(day: 4, hour: 7, minute: 20),
                      endDate: .default(day: 4, hour: 8, minute: 0),
                      latitude: 37.331,
                      longitude: -121.894,
                      moreInfoLink: "https://dubdub.fitness/run.html"),
            
            JSONEvent(id: "MicroblogMeetup",
                      tag: .meetup,
                      title: "Micro.blog Meetup",
                      description: "The 3rd Annual Micro.blog meetup during WWDC week in San Jose for anyone interested in Micro.blog. Meet Manton, Jean, and other microbloggers. Ask questions and share tips.",
                      startDate: .default(day: 4, hour: 12, minute: 0, second: 0),
                      endDate: .default(day: 4, hour: 14, minute: 0, second: 0),
                      place: "Outside Grace Deli",
                      latitude: 37.3287,
                      longitude: -121.8916,
                      ticketLink: "https://docs.google.com/forms/d/e/1FAIpQLSfD5ItpNQ9DMoZJuAG54Kuv0UyD0sy2dt5Pr55KhWfAf0yM0Q/viewform"),
            
            JSONEvent(id: "VaporAtWWDC",
                      tag: .meetup,
                      title: "Vapor @ WWDC Meetup",
                      description: "A meetup to talk about all things server-side Swift and Vapor for those attending WWDC, AltConf or nearby! Location is not yet confirmed (but possibly San Pedro Square).",
                      startDate: .default(day: 4, hour: 19, minute: 0),
                      endDate: .default(day: 4, hour: 22, minute: 0),
                      place: "San Pedro Square",
                      latitude: 37.3355,
                      longitude: -121.8921,
                      ticketLink: "https://www.meetup.com/Vapor-WWDC/events/261508450/"),
            
            JSONEvent(id: "DubDubClimb050619",
                      tag: .meetup,
                      title: "Dub Dub Climb",
                      description: "What started as a few WWDC participants hitting the rock gym is evolving! Begin your day with a fun indoor climb while meeting other WWDC folks and chatting about all the announcements, afterparties and more!",
                      startDate: .default(day: 5, hour: 7, minute: 15),
                      endDate: .default(day: 5, hour: 8, minute: 30),
                      place: "The Studio",
                      latitude: 37.330321,
                      longitude: -121.88577,
                      moreInfoLink: "https://dubdub.fitness/climb.html"),
            
            JSONEvent(id: "DubDubRun050619",
                      tag: .meetup,
                      title: "Dub Dub Run",
                      description: "Kick off your mornings right with an easy 5k jog along the scenic Guadalupe River while chattting about all the fun stuff announced at WWDC.",
                      startDate: .default(day: 5, hour: 7, minute: 20),
                      endDate: .default(day: 5, hour: 8, minute: 0),
                      latitude: 37.331,
                      longitude: -121.894,
                      moreInfoLink: "https://dubdub.fitness/run.html"),
            
            JSONEvent(id: "CallForCodeWorkshopDay",
                      tag: .meetup,
                      title: "IBM Call for Code Workshop Day",
                      description: "Bring your Mac or use one of ours and go deep into the latest enterprise-ready mobile, machine learning, and cloud technologies available for iOS developers. During the day, there are 2 workshops which go in depth into Machine Learning and Server-side Swift. No registration required as these are first-come, first-serve workshops.",
                      startDate: .default(day: 5, hour: 9, minute: 0, second: 0),
                      endDate: .default(day: 5, hour: 16, minute: 0, second: 0),
                      place: "Willow Glenn Conference Room, San Jose Marriott",
                      latitude: 37.3302,
                      longitude: -121.8885,
                      moreInfoLink: "https://developer.ibm.com/announcements/wwdc-call-for-code-workshop-day/"),
            
            JSONEvent(id: "CallForCodeReception",
                      tag: .meetup,
                      title: "IBM Call for Code Reception",
                      description: "End your day at Apple’s Worldwide Developer’s Conference at IBM’s Call for Code Reception and discover how you and your peers can make a difference in solving society’s most pressing issues. This is your chance to connect with fellow developers for fun and refreshments.",
                      startDate: .default(day: 5, hour: 18, minute: 30, second: 0),
                      endDate: .default(day: 5, hour: 20, minute: 30, second: 0),
                      place: "Continental Bar Lounge and Patio",
                      latitude: 37.3308,
                      longitude: -121.8869,
                      ticketLink: "http://ibm.biz/Call4Code-SJ",
                      moreInfoLink: "https://developer.ibm.com/blogs/connect-with-ibm-altconf-wwdc-2019"),
            
            JSONEvent(id: "DubDubClimb060619",
                      tag: .meetup,
                      title: "Dub Dub Climb",
                      description: "What started as a few WWDC participants hitting the rock gym is evolving! Begin your day with a fun indoor climb while meeting other WWDC folks and chatting about all the announcements, afterparties and more!",
                      startDate: .default(day: 6, hour: 7, minute: 15),
                      endDate: .default(day: 6, hour: 8, minute: 30),
                      place: "The Studio",
                      latitude: 37.330321,
                      longitude: -121.88577,
                      moreInfoLink: "https://dubdub.fitness/climb.html"),
            
            JSONEvent(id: "DubDubRun060619",
                      tag: .meetup,
                      title: "Dub Dub Run",
                      description: "Kick off your mornings right with an easy 5k jog along the scenic Guadalupe River while chattting about all the fun stuff announced at WWDC.",
                      startDate: .default(day: 6, hour: 7, minute: 20),
                      endDate: .default(day: 6, hour: 8, minute: 0),
                      latitude: 37.331,
                      longitude: -121.894,
                      moreInfoLink: "https://dubdub.fitness/run.html"),
            
            JSONEvent(id: "LadiesAtWWDC",
                      tag: .meetup,
                      title: "Ladies at WWDC Dinner",
                      description: "Enjoy an evening of fun networking, delicious appetizers, awesome swag, and one-of-a-kind cocktails with your fellow women-in-tech during WWDC.",
                      startDate: .default(day: 6, hour: 17, minute: 0, second: 0),
                      endDate: .default(day: 6, hour: 20, minute: 0, second: 0),
                      place: "Social Lady Bar and Restaurant",
                      latitude: 37.3352,
                      longitude: -121.8878,
                      ticketLink: "https://ti.to/iOS-meetups/ladies-at-wwdc"),
            
            JSONEvent(id: "NightOfDimSum060619",
                      tag: .meetup,
                      title: "Night of Dim Sum 2019",
                      description: "Join us for a night of all-you-can-eat dim sum! Located just a couple of miles from downtown San Jose in the Westfield Valley Fair Mall (where there is also an Apple Store and a LEGO store), Din Tai Fung is internationally known as one of the world's best Shanghai dumpling restaurants.",
                      startDate: .default(day: 6, hour: 19, minute: 0),
                      endDate: .default(day: 6, hour: 21, minute: 0),
                      place: "Din Tai Fung (Westfield Valley Fair Mall)",
                      latitude: 37.3261,
                      longitude: -121.9441,
                      ticketLink: "https://www.eventbrite.com/e/night-of-dim-sum-2019-tickets-54087628553"),
            
            // MARK: Other
            
            JSONEvent(id: "Burritos1",
                      tag: .other,
                      title: "Breakfast Burritos with Embrace",
                      description: "To help fuel developers through the many sessions, meetups, conferences and happy hours during the week of WWDC, Embrace is serving free breakfast burritos! The team will be parked near the convention center handing out breakfast burritos for hungry attendees of WWDC and AltConf.",
                      startDate: .default(day: 4, hour: 8, minute: 0, second: 0),
                      endDate: .default(day: 4, hour: 12, minute: 0, second: 0),
                      latitude: 37.3298,
                      longitude: -121.8888,
                      moreInfoLink: "https://www.eventbrite.com/e/breakfast-burritos-with-embrace-tickets-62308195490"),
            
            JSONEvent(id: "Burritos2",
                      tag: .other,
                      title: "Breakfast Burritos with Embrace",
                      description: "To help fuel developers through the many sessions, meetups, conferences and happy hours during the week of WWDC, Embrace is serving free breakfast burritos! The team will be parked near the convention center handing out breakfast burritos for hungry attendees of WWDC and AltConf.",
                      startDate: .default(day: 5, hour: 8, minute: 0, second: 0),
                      endDate: .default(day: 5, hour: 12, minute: 0, second: 0),
                      latitude: 37.3298,
                      longitude: -121.8888,
                      moreInfoLink: "https://www.eventbrite.com/e/breakfast-burritos-with-embrace-tickets-62308195490"),
            
            JSONEvent(id: "TrySwiftSanJose",
                      tag: .other,
                      title: "try! Swift San Jose",
                      description: "try! Swift is an international community gathering about the latest advancements in Swift Development, all about bringing together talent from all around the world to collaborate and share advanced knowledge and techniques to improve Swift craftsmanship.",
                      startDate: .default(day: 7, hour: 10, minute: 0),
                      endDate: .default(day: 7, hour: 17, minute: 0),
                      place: "Hilton San Jose",
                      latitude: 37.3293,
                      longitude: -121.8905,
                      ticketLink: "https://www.tryswift.co/events/2019/sanjose/")
        ]
    }
}
